eck-beats:
  enabled: true
  name: metricbeat
  spec:
    type: metricbeat
    version: 8.9.0-SNAPSHOT
    elasticsearchRef:
      name: NAME
    kibanaRef:
      name: NAME
    daemonSet:
      podTemplate:
        spec:
          containers:
            - args:
                - -e
                - -c
                - /etc/beat.yml
                - -system.hostfs=/hostfs
              name: metricbeat